import type { Settings } from '../../src/db/schema';

/** A complete Settings row with neutral defaults, for scheduler tests. */
export const baseSettings: Settings = {
  userId: 'u1',
  dayStartMinutes: 7 * 60,
  dayEndMinutes: 22 * 60 + 30,
  sleepStartMinutes: 60,
  sleepTargetMinutes: 8 * 60,
  wakeBufferMinutes: 30,
  morningEndMinutes: 13 * 60,
  afternoonEndMinutes: 18 * 60,
  minBlockMinutes: 20,
  maxBlockMinutes: 90,
  breakMinutes: 10,
  bufferAroundEventsMinutes: 15,
  universityTravelMinutes: 20,
  universityToWorkTravelMinutes: 25,
  universityPreparationMinutes: 60,
  universityShowerPreparationMinutes: 105,
  universityShowerDefault: false,
  restaurantTravelMinutes: 20,
  restaurantReturnMinutes: 20,
  travelMode: 'bike',
  homeAddress: null,
  defaultTravelMinutes: 20,
  travelBufferMinutes: 5,
  placeTravelMinutes: '',
  gymSessionsPerWeek: 0,
  gymMaxSessionsPerWeek: 4,
  gymDurationMinutes: 75,
  gymPreferredDays: '1,3,5',
  gymAvoidDays: '',
  gymTravelMinutes: 25,
  gymPreparationMinutes: 20,
  gymReturnMinutes: 25,
  gymMinRecoveryHours: 36,
  briefingMinutes: 7 * 60,
  reviewMinutes: 20 * 60 + 30,
  reviewAfterShiftMinutes: 30,
  fixedEventKeywords: 'turno,lezione',
  planningHorizonDays: 14,
  autoRescheduleEnabled: true,
  pushEnabled: true,
  updatedAt: Date.now(),
};
